before_install:
  - "gem install bundler"
before_script:
  - "bundle exec rake test_app"
script:
  - "bundle exec rspec spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby
  - rbx
env:
  - DB=sqlite
language: ruby
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx
    - rvm: jruby
